export enum AuthErrorType {
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_BLACKLISTED = 'TOKEN_BLACKLISTED',
  USER_BLOCKED = 'USER_BLOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  DUPLICATE_DATA = 'DUPLICATE_DATA',
  OTP_EXPIRED = 'OTP_EXPIRED',
  INVALID_OTP = 'INVALID_OTP',
  ACCESS_DENIED = 'ACCESS_DENIED',
}
