FROM node:22.14.0

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

# Copy prisma schema specifically and generate the Linux binary
COPY prisma ./prisma/
RUN npx prisma generate

# Copy source AFTER install
COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]
