import { TEnv } from '@/app/@types/system.types';
import { getEnv } from '@/app/utils/env.utils';

export const env: TEnv = {
  NODE_ENV: getEnv('NODE_ENV'),
  JWT_ACCESS_TOKEN_SECRET_KEY: getEnv('JWT_ACCESS_TOKEN_SECRET_KEY'),
  JWT_REFRESH_TOKEN_SECRET_KEY: getEnv('JWT_REFRESH_TOKEN_SECRET_KEY'),
  SMTP_HOST: getEnv('SMTP_HOST'),
  SMTP_PORT: Number(getEnv('SMTP_PORT')),
  SMTP_USER: getEnv('SMTP_USER'),
  SMTP_PASS: getEnv('SMTP_PASS'),
  OTP_HASH_SECRET: getEnv('OTP_HASH_SECRET'),
  REDIS_HOST: getEnv('REDIS_HOST'),
  REDIS_PASSWORD: getEnv('REDIS_PASSWORD'),
  REDIS_PORT: Number(getEnv('REDIS_PORT')),
  JWT_VERIFY_OTP_PAGE_SECRET_KEY: getEnv('JWT_VERIFY_OTP_PAGE_SECRET_KEY'),
  S3_ACCESS_KEY: getEnv('S3_ACCESS_KEY'),
  S3_SECRET_KEY: getEnv('S3_SECRET_KEY'),
  S3_REGION: getEnv('S3_REGION'),
  S3_BUCKET_NAME: getEnv('S3_BUCKET_NAME'),
  STRIPE_API_SECRET_KEY: getEnv('STRIPE_API_SECRET_KEY'),
  // STRIPE_WEBHOOK_SECRET_KEY: getEnv('STRIPE_WEBHOOK_SECRET_KEY'),
  FIREBASE_ACCOUNT_TYPE: getEnv('FIREBASE_ACCOUNT_TYPE'),
  FIREBASE_PROJECT_ID: getEnv('FIREBASE_PROJECT_ID'),
  FIREBASE_PRIVATE_KEY_ID: getEnv('FIREBASE_PRIVATE_KEY_ID'),
  FIREBASE_PRIVATE_KEY: getEnv('FIREBASE_PRIVATE_KEY'),
  FIREBASE_CLIENT_ID: getEnv('FIREBASE_CLIENT_ID'),
  FIREBASE_AUTH_URI: getEnv('FIREBASE_AUTH_URI'),
  FIREBASE_TOKEN_URI: getEnv('FIREBASE_TOKEN_URI'),
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL: getEnv(
    'FIREBASE_AUTH_PROVIDER_X509_CERT_URL'
  ),
  FIREBASE_CLIENT_X509_CERT_URL: getEnv('FIREBASE_CLIENT_X509_CERT_URL'),
  FIREBASE_UNIVERSE_DOMAIN: getEnv('FIREBASE_UNIVERSE_DOMAIN'),
  FIREBASE_CLIENT_EMAIL: getEnv('FIREBASE_CLIENT_EMAIL'),
  GEO_PROVIDER: getEnv('GEO_PROVIDER'),
  GOOGLE_MAPS_API_KEY: getEnv('GOOGLE_MAPS_API_KEY'),
};
