FROM node:22.14.0
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

# Copy prisma schema specifically and generate the Linux binary
COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

CMD ["ts-node", "--transpile-only", "--require", "tsconfig-paths/register", "./src/workers/index.ts"]