name: DEPLOY DEVELOPMENT

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /root/abdullah_projects/mohammad-event-management
            git fetch origin
            git switch development || git checkout development
            git reset --hard origin/development
            npm install
            docker compose down
            docker compose up -d --build
            export CI=true
            npm run migrate:generate
